"""empty message

Revision ID: 031a9f693983
Revises: 0004
Create Date: 2026-04-07 13:24:40.491014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031a9f693983'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_events', sa.Column('thread_id', sa.UUID(), nullable=True))
    # Backfill existing rows: default thread_id to trace_id
    op.execute('UPDATE message_events SET thread_id = trace_id WHERE thread_id IS NULL')
    op.alter_column('message_events', 'thread_id', nullable=False)
    op.create_index('ix_message_events_thread_id', 'message_events', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_events_thread_id', table_name='message_events')
    op.drop_column('message_events', 'thread_id')
    # ### end Alembic commands ###
