"""add message_events table

Revision ID: 4579e584980f
Revises: 0003
Create Date: 2026-04-05 18:00:52.885592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4579e584980f'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('structured', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_message_events_created_at', 'message_events', ['created_at'], unique=False)
    op.create_index('ix_message_events_idempotency_key', 'message_events', ['idempotency_key'], unique=False)
    op.create_index('ix_message_events_trace_id', 'message_events', ['trace_id'], unique=False)
    op.drop_index(op.f('ix_system_heartbeats_id'), table_name='system_heartbeats')
    op.drop_index(op.f('ix_system_heartbeats_run_id'), table_name='system_heartbeats')
    op.drop_index(op.f('ix_system_heartbeats_ts'), table_name='system_heartbeats')
    op.drop_table('system_heartbeats')
    op.add_column('task_steps', sa.Column('risk_level', sa.Text(), server_default='low', nullable=False))
    op.add_column('task_steps', sa.Column('pending_approval_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_steps', 'pending_approval_id')
    op.drop_column('task_steps', 'risk_level')
    op.create_table('system_heartbeats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('uptime_s', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_heartbeats_pkey'))
    )
    op.create_index(op.f('ix_system_heartbeats_ts'), 'system_heartbeats', ['ts'], unique=False)
    op.create_index(op.f('ix_system_heartbeats_run_id'), 'system_heartbeats', ['run_id'], unique=False)
    op.create_index(op.f('ix_system_heartbeats_id'), 'system_heartbeats', ['id'], unique=False)
    op.drop_index('ix_message_events_trace_id', table_name='message_events')
    op.drop_index('ix_message_events_idempotency_key', table_name='message_events')
    op.drop_index('ix_message_events_created_at', table_name='message_events')
    op.drop_table('message_events')
    # ### end Alembic commands ###
