"""init

Revision ID: f39fed3a5b4c
Revises: 0001
Create Date: 2026-03-27 01:18:22.618807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f39fed3a5b4c'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_heartbeats_id'), table_name='system_heartbeats')
    op.drop_index(op.f('ix_system_heartbeats_run_id'), table_name='system_heartbeats')
    op.drop_index(op.f('ix_system_heartbeats_ts'), table_name='system_heartbeats')
    op.drop_table('system_heartbeats')
    op.alter_column('audit_events', 'audit_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='audit_id::uuid')
    op.alter_column('audit_events', 'timestamp',
               existing_type=sa.VARCHAR(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               postgresql_using='timestamp::timestamptz')
    op.alter_column('audit_events', 'stage',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('audit_events', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('audit_events', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('audit_events', 'outcome',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('audit_events', 'ref_event_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='ref_event_id::uuid')
    op.alter_column('audit_events', 'ref_task_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='ref_task_id::uuid')
    op.alter_column('audit_events', 'ref_step_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='ref_step_id::uuid')
    op.alter_column('audit_events', 'ref_tool_call_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='ref_tool_call_id::uuid')
    op.alter_column('audit_events', 'ref_approval_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='ref_approval_id::uuid')
    op.alter_column('audit_events', 'tool_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_events', 'connector_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_events', 'risk_level',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_events', 'autonomy_level',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_events', 'payload_ref',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('ix_audit_events_timestamp', 'audit_events', ['timestamp'], unique=False)
    op.create_index('ix_audit_events_trace_id', 'audit_events', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_events_trace_id', table_name='audit_events')
    op.drop_index('ix_audit_events_timestamp', table_name='audit_events')
    op.alter_column('audit_events', 'payload_ref',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audit_events', 'autonomy_level',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audit_events', 'risk_level',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audit_events', 'connector_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audit_events', 'tool_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audit_events', 'ref_approval_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audit_events', 'ref_tool_call_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audit_events', 'ref_step_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audit_events', 'ref_task_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audit_events', 'ref_event_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audit_events', 'outcome',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('audit_events', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('audit_events', 'type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('audit_events', 'stage',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('audit_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('audit_events', 'audit_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('system_heartbeats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('uptime_s', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_heartbeats_pkey'))
    )
    op.create_index(op.f('ix_system_heartbeats_ts'), 'system_heartbeats', ['ts'], unique=False)
    op.create_index(op.f('ix_system_heartbeats_run_id'), 'system_heartbeats', ['run_id'], unique=False)
    op.create_index(op.f('ix_system_heartbeats_id'), 'system_heartbeats', ['id'], unique=False)
    # ### end Alembic commands ###
